# Generated by Django 4.2.4 on 2024-04-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_register_conformpassword_register_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="Address",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="register",
            name="Email",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="register",
            name="conformpassword",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="register",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="register",
            name="password",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="register",
            name="phone",
            field=models.CharField(max_length=12),
        ),
    ]
