# Generated by Django 4.2.4 on 2024-04-24 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_deposit_delete_contribution"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deposit",
            old_name="amount",
            new_name="time",
        ),
        migrations.RenameField(
            model_name="deposit",
            old_name="user",
            new_name="userid",
        ),
    ]
