# Generated by Django 4.2.4 on 2024-04-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0008_deposit_delete_transactions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deposit",
            name="amount",
        ),
        migrations.AddField(
            model_name="deposit",
            name="rupee",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="userid",
            field=models.IntegerField(),
        ),
    ]
