# Generated by Django 4.2.4 on 2024-04-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0009_remove_deposit_amount_deposit_rupee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Draw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.IntegerField()),
                ("rupee", models.IntegerField(default=100)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
