# Generated by Django 4.2.4 on 2024-04-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0010_draw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="Address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="register",
            name="Email",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="register",
            name="conformpassword",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="register",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="register",
            name="password",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="register",
            name="phone",
            field=models.CharField(max_length=100),
        ),
    ]
