# Generated by Django 4.2.4 on 2024-04-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0011_alter_register_address_alter_register_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Win",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.IntegerField()),
                ("eighty", models.CharField(max_length=100)),
                ("five", models.CharField(max_length=100)),
                ("fifteen", models.CharField(max_length=100)),
            ],
        ),
    ]
