# Generated by Django 4.2.4 on 2024-04-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0012_win"),
    ]

    operations = [
        migrations.AddField(
            model_name="win",
            name="total",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
