# Generated by Django 4.2.4 on 2024-04-30 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0016_rename_eight_win_eighty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="win",
            old_name="eighty",
            new_name="eight",
        ),
    ]
