# Generated by Django 4.2.4 on 2024-04-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0017_rename_eighty_win_eight"),
    ]

    operations = [
        migrations.AddField(
            model_name="win",
            name="date",
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
