# Generated by Django 4.2.4 on 2024-04-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0019_alter_win_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="win",
            name="date",
            field=models.DateField(),
        ),
    ]
